name: Publish Package to npmjs

permissions:
  id-token: write

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          cargo install wasm-pack
          npm ci
      - name: Publish
        run: |
          cd lib
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
